import type { DashboardData, EventDetails, MedicineRow } from './types';

export const dashboardData: DashboardData = {
    summary: [
        {
            id: 1,
            title: 'Medicine #580',
            subtitle: 'Awaiting results',
            value: '',
            variant: 'success',
        },
        {
            id: 2,
            title: '3 vaccines',
            subtitle: 'On hold',
            value: '',
            variant: 'warning',
        },
        {
            id: 3,
            title: '15 products',
            subtitle: 'Out of stock',
            value: '',
            variant: 'danger',
        },
    ],
    totalTests: [
        { name: '01 May', received: 20, completed: 30 },
        { name: '03 May', received: 32, completed: 26 },
        { name: '05 May', received: 32, completed: 25 },
        { name: '08 May', received: 28, completed: 25 },
        { name: '12 May', received: 28, completed: 25 },
        { name: '15 May', received: 45, completed: 25 },
        { name: '18 May', received: 58, completed: 50 },
        { name: '21 May', received: 82, completed: 50 },
        { name: '24 May', received: 50, completed: 70 },
        { name: '27 May', received: 30, completed: 42 },
        { name: '30 May', received: 35, completed: 56 },
    ],
    testedDrugs: [
        { name: 'Mon', value: 40 },
        { name: 'Tue', value: 52 },
        { name: 'Wed', value: 45 },
        { name: 'Thu', value: 31 },
        { name: 'Fri', value: 55 },
        { name: 'Sat', value: 38 },
        { name: 'Sun', value: 47 },
    ],
    approvalRates: [
        { name: '01 May', value: 30 },
        { name: '02 May', value: 28 },
        { name: '03 May', value: 36 },
        { name: '04 May', value: 26 },
        { name: '05 May', value: 52 },
        { name: '06 May', value: 45 },
        { name: '07 May', value: 60 },
    ],
    testingProcess: [
        { name: 'Preclinical testing', value: 72 },
        { name: 'Clinical trials', value: 18 },
        { name: 'Regulatory approval', value: 10 },
    ],
};

export const medicines: MedicineRow[] = [
    {
        id: 47890,
        name: 'Medicine #47890',
        location: 'Serenity Health Clinic',
        startDate: 'Dec 12, 2018',
        endDate: 'Dec 12, 2026',
        successReaction: true,
        processCurrent: 145,
        processTotal: 223,
        status: { blue: 25, red: 20, orange: 15, green: 40 },
    },
    {
        id: 56813,
        name: 'Medicine #56813',
        location: 'Vitality Medical Center',
        startDate: 'Jan 9, 2019',
        endDate: 'Dec 9, 2022',
        successReaction: false,
        processCurrent: 145,
        processTotal: 145,
        status: { blue: 35, red: 25, orange: 15, green: 25 },
    },
    {
        id: 490,
        name: 'Vaccine #490',
        location: 'Oasis Medical Institute',
        startDate: 'Sep 4, 2019',
        endDate: 'Dec 4, 2021',
        successReaction: true,
        processCurrent: 18,
        processTotal: 56,
        status: { blue: 20, red: 10, orange: 15, green: 55 },
    },
    {
        id: 987,
        name: 'Vaccine #987',
        location: 'Summit Health Institute',
        startDate: 'Nov 1, 2019',
        endDate: 'Dec 1, 2024',
        successReaction: true,
        processCurrent: 277,
        processTotal: 539,
        status: { blue: 25, red: 35, orange: 10, green: 30 },
    },
    {
        id: 45,
        name: 'Medicine #45',
        location: 'Prosperity Medical Practice',
        startDate: 'Dec 28, 2019',
        endDate: 'Nov 28, 2021',
        successReaction: false,
        processCurrent: 169,
        processTotal: 396,
        status: { blue: 55, red: 20, orange: 10, green: 15 },
    },
    {
        id: 413,
        name: 'Vaccine #413',
        location: 'Harmony Healthcare Group',
        startDate: 'Feb 12, 2019',
        endDate: 'Nov 30, 2022',
        successReaction: true,
        processCurrent: 600,
        processTotal: 600,
        status: { blue: 30, red: 25, orange: 15, green: 30 },
    },
];

export const eventDetails: EventDetails = {
    title: 'Migracalm-X - new drug testing for chronic migraine',
    place: 'Tavern on the Greend, New York',
    address: '434 Rockaway Ave, Brooklyn New York, 11212-5636',
    date: '28th — 2nd July 2022',
    time: '10 am - 4 pm Eastern Daylight Time',
    manufacturer: 'Serenity Health Clinic',
    mapImageUrl:
        'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=900&q=80',
    tags: ['Medicine #459026', 'Vaccine #78'],
    description:
        'We will be conducting clinical trials of the new drug “Migracalm-X”, which is designed to treat acute forms of migraines. We are going to test its effectiveness on 20 patients who have been suffering from this disorder for many years. The upcoming clinical trials will allow us to evaluate the safety and efficacy of the drug, as well as obtain important data for its registration and release on the market.',
};